AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Creating PKG basic backend environment.
Parameters:
  EnvName:
    Description: "Your environment name here"
    Type: String
    Default: defalt
  CloudWatchAlarmEmail:
    Description: "The e-mail to notify errors"
    Type: String
    Default: ""

Resources:
  StreamDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "five-stream-data-bucket-${EnvName}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true

  PKGKinesisFirehose:
    Type: AWS::KinesisFirehose::DeliveryStream
    DependsOn: StreamDataBucket
    Properties:
      DeliveryStreamName: !Sub PKG_stream_${EnvName}
      DeliveryStreamType: DirectPut
      ExtendedS3DestinationConfiguration:
        BucketARN: !Sub "arn:aws:s3:::five-stream-data-bucket-${EnvName}"
        BufferingHints:
          SizeInMBs: 64
          IntervalInSeconds: 60
        ErrorOutputPrefix: error/
        Prefix: uuid/!{partitionKeyFromQuery:uuid}/
        RoleARN: !Sub "${FirehoseRole.Arn}"
        DynamicPartitioningConfiguration:
          Enabled: true
        ProcessingConfiguration:
          Enabled: "true"
          Processors:
            - Type: MetadataExtraction
              Parameters:
                - ParameterName: MetadataExtractionQuery
                  ParameterValue: "{uuid:.uuid}"
                - ParameterName: JsonParsingEngine
                  ParameterValue: JQ-1.6

  FirehoseRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub five_firehose_role_${EnvName}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - firehose.amazonaws.com
            Action:
              - sts:AssumeRole

  DeliveryPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub firehose_delivery_policy_${EnvName}
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:PutObject
            Resource:
              - !Sub "arn:aws:s3:::${StreamDataBucket}/*"
      Roles:
        - !Ref "FirehoseRole"